// Generated by CoffeeScript 1.4.0
(function() {
  var where,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  beforeEach(function() {
    var alreadyDefined, suite, symbol, _fn, _results,
      _this = this;
    alreadyDefined = [];
    suite = this.suite;
    _results = [];
    while (suite != null) {
      if (suite.wheres_ != null) {
        _fn = function(suite, symbol) {
          var f;
          f = function() {
            return suite.wheres_[symbol].apply(_this);
          };
          return Object.defineProperty(_this, symbol, {
            get: function() {
              return tap(f(), function(v) {
                return f = function() {
                  return v;
                };
              });
            },
            set: function(v) {
              return f = function() {
                return v;
              };
            }
          });
        };
        for (symbol in suite.wheres_) {
          if (__indexOf.call(alreadyDefined, symbol) >= 0) {
            continue;
          }
          alreadyDefined.push(symbol);
          _fn(suite, symbol);
        }
      }
      _results.push(suite = suite.parentSuite);
    }
    return _results;
  });

  window.where = where = function(symbol, definition) {
    var s;
    s = jasmine.getEnv().currentSuite;
    if (s == null) {
      throw "Where called outside of a declaring suite!";
    }
    s.wheres_ = s.wheres_ || {};
    return s.wheres_[symbol] = function() {
      return definition.apply(this);
    };
  };

  window.subject = function(f) {
    return where("subject", f);
  };

}).call(this);
